### ISSUE TITLE
Error handling middleware

### ISSUE THREAD

**Issue by Kamahl19** [pburtchaell/redux-promise-middleware#135]
Hi,

I have gone through all the issues to find the proper way to handle rejected promises, but I still have an issue.

I use slightly customized error-middleware from [complex example](https://github.com/pburtchaell/redux-promise-middleware/blob/master/examples/complex/middleware/error.js).

**TLDR:**
If using error middlware, dispach returns resolved promise even though payload.promise throws an error. If not using error middleware, dispatch returns rejected promise. 

**Longer explanation:**
When I call an action with promise, which rejects, error middleware catches and logs this error. However the error continues to the chained .then() method, in my action creator. In the .then() I get the error, instead of { value, action } object. When I dont use error middleware, rejected promise does not fall into the .then() but I have to catch it manually with .catch() in every actionCreator.

**Error middleware:**
```js
export default function errorMiddleware() {
    return (next) => (action) => {
        const result = next(action);

        if (!isPromise(result)) {
            return action;
        }

        if (action.meta && action.meta.globalError) {
            return result.catch((error) => {
                console.warn(`${action.type} caught at middleware with reason: ${JSON.stringify(error.message)}.`);

                return error;
            });
        }

        return result;
    };
}
```

**Action creator:**
```js
export const actionCreator = () =>
    (dispatch) =>
        dispatch({
            type: ACTION_TYPE,
            meta: { globalError: true },
            payload: Promise.reject('an error occured'),
        })
        .then((res) => {
            console.log(res); // an error occured
        });
```

I have also noticed that in the error middleware in the complex example, you do 
```js
if (!isPromise(result)) {
     return action;
}
```

Should it not `return next(action)` ?

**Comment by pburtchaell** [comment]
> Should it not `return next(action)`?

It should, thanks!. Patched in https://github.com/pburtchaell/redux-promise-middleware/commit/6157819b143d1d1909288b782561d6634c2471f5.

> If using error middleware, dispatch returns resolved promise even though `payload.promise` throws an error. If not using error middleware, dispatch returns rejected promise.

Right, this is expected behavior of promises. If you `catch` a rejected promise and call `then`, the fulfilled handler is called, not the rejected handler. Here is a [JSBin demonstrating this behavior](https://jsbin.com/bowehihoce/edit?js,console,output). "Option A," from the JSBin is what the error middleware uses. If you uncomment the other options, you can see how the behavior changes.

The point of the global error middleware is to catch any errors not caught at the action creator. For example, say you have an action creator that does not use thunks. It returns an object instead of a function. 

```js
// OPTION A: handle error in middleware 
const rejectedActionCreator = message => {
  type: 'GLOBAL_ERROR',
  payload: Promise.reject(new Error('foo'))
};
```

For this action creator, the error would be "uncaught." For some developers, it is annoying to have that uncaught promise error in the console and he/she does not want to add error handling to every action creator. The middleware solves this problem by "globally" catching [certain errors](https://github.com/pburtchaell/redux-promise-middleware/blob/master/examples/complex/middleware/error.js#L26). 

On the other hand, if your action creator uses thunks, the promise will be returned by the action creator and you can catch the error "at the action creator." 

```js
// OPTION B: handle error at action creator
const rejectedActionCreator = message => dispatch => dispatch({
  type: 'LOCAL_ERROR',
  payload:Promise.reject(new Error('foo'))
}).catch(error => {
  dispatch(handleError());
});
```

Essentially with this pattern, you use one or the other—middleware or action creator—to catch errors. Right now, with your action creator, you doing both, which is an antipattern.

Let me know if that make sense. I'm happy to help! I added some tests to the example in https://github.com/pburtchaell/redux-promise-middleware/commit/2eb8e73c221b724767f4d14c0afdf7183384f64b, which might be helpful.

**Comment by Kamahl19** [comment]
Stupid me! Of course it will fall into onFullfill once catched. Somehow I did not realised thats what's happening. Thanks for explanation. 

I think is still not clear to me though. How would you do fetch data, catch error if server responds with error and if not, redirected to '/' or did some other action..

```js
export const actionCreator = () =>
    (dispatch) =>
        dispatch({
            type: ACTION_TYPE,
            meta: { globalError: true },
            payload: Promise.reject('an error occured'),
        })
        .then((res) => {
            redirectTo('/');
        });
```

**Comment by pburtchaell** [comment]
> How would you do fetch data, catch error if server responds with error

This is outside the scope of this project, so I can't provide too much information. I use the Fetch API and evaluate the response status. Fetch works best with the async code because it returns a promise.

For example: 

```js
fetch(url, options).then(response => {
  // throw an error if status is not in 200 OK range
  if (response.status >= 200 && response.status < 300) {
    return response;
  } else {
    throw new Error(response.status);
  }
});
```

And then, in your action creator:

```js
export const actionCreator = () =>
    (dispatch) =>
        dispatch({
            type: ACTION_TYPE,
            payload: fetch(url, options).then(...),
        })
        .then(() => {
            dispatch(redirectTo('/')); // use action creators to change router location
        });
```

I'd suggest referencing the [Redux Async Actions documentation](http://redux.js.org/docs/advanced/AsyncActions.html#async-action-creators).

**Comment by Darmikon** [comment]
Hi there. 
In my opinion the work of error handling is a bit weird.

You have written
```
 It is your responsibility to catch the errors and not the responsibility of redux-promise-middleware
```

I use async function and it's normal for me to use `throw` everywhere.


Look at the example

```
export function load(){
	return dispatch => {
		return dispatch({
			type: LOAD
			, payload: new Promise((resolve,reject) => {
				//throw new Error('custom - error'); // throw an error
				reject('custom')
			})
		})
	}
}

```

in both cases: `throw` and `reject` your middleware works fine at first and reducer action 
LOAD_REJECTED is triggered. Therefore reducer can update state. However exactly after that I see 
```
Uncaught (in promise) custom :4000/#/redux-form/Form:1 
```

If you've already catched an exception and react properly on it. 
Then why the exception is still uncaught?

Moreover
```
export function foo() {
  return dispatch => dispatch({
    type: 'FOO_ACTION',
    payload: new Promise(() => {
      throw new Error('foo');
    })
  }).catch(error => {
    // catch and handle error
  });
}
```

this syntax from your example triggers `_FULFILLED` action and not `_REJECTED`.
It's because this promise is considered as resolved and not rejected.

So please clearify what is the proper way to handle errors without uncaught exceptions using your api.
Maybe some working example?

Thanks

**Comment by elcorders** [comment]
I'm having the same conundrum as @Darmikon is! and may we know why is this closed ❓

**Comment by janhoogeveen** [comment]
This helps a bit in explaining the rationale behind the design: https://github.com/pburtchaell/redux-promise-middleware/blob/master/docs/guides/rejected-promises.md

However, a lot of times I just want errors to fail silently. I trust my reducer to do the job for me. The most easy fix is to simply swallow the error manually in your action creator in the .catch method.

```js
export function promiseAction() {
  return dispatch => dispatch({
    type: PROMISE,
    payload: new Promise((resolve, reject) => {
      setTimeout(() => {
        if (Math.random() > 0.5) {
          reject('promise failed');
        } else {
          resolve('promise OK');
        }
      }, 1000);
    }),
  }).catch(() => {});
}

```
