### ISSUE TITLE
How to update error state from middleware (Question not Issue)

### ISSUE THREAD

**Issue by EmirGluhbegovic** [pburtchaell/redux-promise-middleware#174]
Good day,

I have redux-promise-middleware working. I have also created the error middleware class as per the complex example (somewhat differently). I am catching the rejected promises. I now want to take the error message and update the error state to show the issue on the layout.

2 things I am unsure of: 
1) How to take the error message caught in the middleware and update the state.
2) How to make the error component be aware of the state update so it re-renders to show/not show the error.

I am new to redux so that is part of my challenge also.

**Comment by pburtchaell** [comment]
>  I now want to take the error message and update the error state to show the issue on the layout.

In Redux, changes to the state tree are always described by actions. Since your goal is to update state, you need some action that that describe the change you want to make to the state.

I would recommend you either:
- (a) evaluate the rejected promise action or
- (b) dispatch an action from your error middleware.

As far as Redux Promise Middleware is concerned, it doesn't really matter where you do this. It's not related to the job this middleware has. Does that make sense?

**Comment by pburtchaell** [comment]
Closing because I answered the question 7 days ago. Please reopen if necessary.
