### ISSUE TITLE
Catching Rejected Promise Results In 'Fulfilled' Promise Type

### ISSUE THREAD

**Issue by maxwell-oroark** [pburtchaell/redux-promise-middleware#186]
I understand that its the application's responsibility to catch errors like you mention in the guide documentation but I wish to catch the error and have access to the _REJECTED promise dispatch event, is this possible?

If I were to handle the error locally like you instruct, then I have to manually dispatch a _REJECTED action type myself which seems like should be done for me by your library, no?

Thanks!

**Comment by pburtchaell** [comment]
Can you post your code? You should be able to access the REJECTED action in your reducer because it the action dispatched before you handle the error.

**Comment by maxwell-oroark** [comment]
```
return {
      type: types.FETCH_SESSION_SILENT,
      payload: auth0promise.catch( error => error ) // _FULFILLED
    }

return {
      type: types.FETCH_SESSION_SILENT,
      payload: auth0promise // REJECTED BUT NOW UNHANDLED 
    } 
```

**Comment by maxwell-oroark** [comment]
@pburtchaell

**Comment by pburtchaell** [comment]
Please see issue #185. If you want to catch promise errors at the action creator level, you need to do so **after** the action has been dispatched and read by the middleware. 

With this implementation, you catch the error before the middleware reads it as an error:

```js
return {
  type: types.FETCH_SESSION_SILENT,
  payload: auth0promise.catch( error => error ) // _FULFILLED
}
```

This constructs an entirely new **fulfilled** promise. That's why a fulfilled action—and not a rejected action—is dispatched. You need to dispatch the action first, then catch the error.

**Comment by maxwell-oroark** [comment]
Ah I see now, thanks @pburtchaell
