### ISSUE TITLE
Easy migrate from redux-promise

### ISSUE THREAD

**Issue by Semigradsky** [pburtchaell/redux-promise-middleware#192]
Hi guys!

I have the [`redux-promise`](https://github.com/redux-utilities/redux-promise) in my project and I want to migrate to this library.

Without configuration this library I need to change all reducers types from REDUCER_TYPE to REDUCER_TYPE_FULLFILLED. That is not cool.

I found that possible to change default type suffixes and type delimeter in options:
```js
promiseMiddleware({
  promiseTypeSuffixes: [
      'PENDING',
      '', // fullfilled promise
      'REJECTED',
  ],
  promiseTypeDelimiter: '',
})
```
It's almost working but delimiter not changing out of this line of code:
https://github.com/pburtchaell/redux-promise-middleware/blob/0ba20c4aebb151dca7ebea6b47767f22dc1588d2/src/index.js#L16

Is it possible to change this line to smth like this
```js
  const PROMISE_TYPE_DELIMITER = typeof config.promiseTypeDelimiter === 'undefined' ? '_' : config.promiseTypeDelimiter;
```
or make some another possibility to not adding delimeter and suffix for fullfilled reducer?

**Comment by Semigradsky** [comment]
Ha! It's really no needed.
I have wrote simple middleware for removing suffix and it's working great.
```js
function removeFullfilledSuffixMiddleware() {
    return (next) => (action) => next({
        ...action,
        type: action.type.replace(/_FULFILLED$/, ''),
    });
}
```

**Comment by pburtchaell** [comment]
Perfect! Glad you got a solution. 😄 

> REDUCER_TYPE to REDUCER_TYPE_FULLFILLED

This has often been a point of discussion on the middleware issues, but until there's a convincing argument for otherwise, [we believe promise actions should describe the promise state](https://github.com/pburtchaell/redux-promise-middleware/blob/master/docs/guides/design-principles.md#asynchronous-action-objects-describe-the-promise-object-state).

In other words:

- `'FOO'` => describes a promise (not serializable)
- `'FOO_PENDING'` => describes a pending promise state (serializable) 
- `'FOO_REJECTED'` => describes a rejected promise state (serializable) 
- `'FOO_FULFILLED'` => describes a fulfilled promise state (serializable) 

One could argue this is verbose, but I think it's valuable to use descriptive action type strings.

**Comment by pburtchaell** [comment]
Closing because a solution was found.

**Comment by ramiloif** [comment]
I'm migrating right now from redux promise,
The main reason is because the action pending rejected events.
I liked this library finally i'll be able to put progress bar properly
However only on debug I understood why my 'FOO' reducer didn't work.
I see that this issue is closed but I think that the normal (FULFILLED) should be just FOO.
The reason is that in non Promise reducers we use it that way.
