### ISSUE TITLE
Action series\queue (cancel old action or run new one after prev is ended)

### ISSUE THREAD

**Issue by oldwin** [pburtchaell/redux-promise-middleware#214]
Hi everyone

## Version Number
5.1.1

## Code Example
```js
function loadSomeApiData() {
  return {
      type: 'LOAD_SOME_API_DATA',
      async payload() {
        const result = await handleAPI();
        return result;
      },
  };
}
```

```js
// First call
loadSomeApiData();
// Second call
loadSomeApiData();
```
## Expected Behavior
Cancel old loadSomeApiData() or put new one to queue, I want to be sure first loadSomeApiData will not affect to next one. Maybe there is some feature exist to cancel or ignore old calling of loadSomeApiData?

## Actual Behavior
I get result in different order (dependce of network delay, tiemouts, etc). I can get last LOAD_SOME_API_DATA_FULLFILLED for not latest query. How to handle it? Is it possible to run the same actions in parallel way (to be sure first one is ended or force to cancel it?)

**Comment by pburtchaell** [comment]
> Is it possible to run the same actions in parallel way? 
> To be sure first one is ended or force to cancel it?

This sounds like [a race condition](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/race). Races are not a feature of the middleware, but a built-in Promise method.

```js
Promise.race([dispatch(loadSomeApiData()), dispatch(loadSomeApiData())]).then(...)
```

Both actions will be dispatched, but you can handle the side effects of whichever one resolves first.

Because `Promise#race` returns a promise, you could create an action creator that accepts an array of actions and, using [Redux Thunk](https://www.npmjs.com/package/redux-thunk), dispatches them in a race.

## Example

Here's a basic example: https://codepen.io/pburtchaell/pen/yEqExz

In this example, two image requests are made in parallel as a race: 

1. One request to the "Dog API"
2. One request to the "Cat API" 

The requests are racing and the promise will resolve with the payload of the first fulfilled request.

If you look at the logs, you will see something like this:

```
action GET_CAT_PENDING @ 10:00:00.970
action GET_DOG_PENDING @ 10:00:00.974
action RACE_PENDING @ 10:00:00.976
action GET_DOG_FULFILLED @ 10:00:01.239
action RACE_FULFILLED @ 10:00:01.241
action GET_CAT_FULFILLED @ 10:00:01.697
```

As you can see, the `GET_CAT` and `GET_DOG` actions are dispatched and we have a race. The `GET_DOG` action is fulfilled and so is the race. The `GET_CAT` action is later fulfilled, but after the race.

I hope this helps. Let me know if you have any other questions.

**Comment by oldwin** [comment]
Hi @pburtchaell 

Thanks a lot for your answer. Sorry I mean not in parallel way, next action should wait for end of previous one or cancel it. It should be the same action. For example `GET_CAT`, and when you run it twice it should be

```
GET_CAT_PENDING
GET_DOG_FULFILLED
GET_CAT_PENDING
GET_DOG_FULFILLED
```

Now it can be
```
GET_CAT_PENDING
GET_CAT_PENDING
GET_DOG_FULFILLED
GET_DOG_FULFILLED
```

In the case first API resonse has bigger API response then time to run next action + second API response.

So as I understand I need to handle it on my end by using some libs (as Bluebird), or using some timestamp to be sure I will fill my redux storage with right data? If there is no way to handle response order in lib and no plans to do it, please close the issue.

Thanks you so much, I'll try to write something with timestamp.

**Comment by pburtchaell** [comment]
No problem! Glad to help. Good luck figuring out the implementation that works. 👍

**Comment by pburtchaell** [comment]
> So as I understand I need to handle it on my end by using some libs (as Bluebird), or using some timestamp to be sure I will fill my redux storage with right data?

Yes. My suggestion would be to chain the two actions (check the examples for a reference) and use Bluebird's approach to add a "canceled" state to the promise.
