### ISSUE TITLE
Something like ACTION_DONE?

### ISSUE THREAD

**Issue by SummerWish** [pburtchaell/redux-promise-middleware#62]
Sometimes we need to change a state when the promise is done/completed (either fulfilled or rejected), such as re-enable the button. It would be helpful and keep DRY if this library could provide such action :-)

**Comment by tomatau** [comment]
A '_FINALLY' would make sense to me yeh, I'm not sure why it wasn't added in the Promise A+ spec but it had some nice use cases! It should be made clear that this action is the very last to be dispatched for a set.

**Comment by pburtchaell** [comment]
I'd rather not include this in the middleware. First, because I want it to follow the specifications and, second, because this is a specific request and I don't think all users of the middleware would benefit from this added feature.

Instead of dispatching a final action for either fulfilled or rejected, you could certainly have a reducer that checks for either the fulfilled or rejected action. Let me know if you need example or if you would like to further discuss. 🙂

**Comment by SummerWish** [comment]
@tomatau Yes! That would be better.

@pburtchaell Thanks! I understand your consideration. Currently I wrote a bunch of exactly the same "FULFILLED" and "REJECTED" reducers, which is the reason I propose this NFR :-)

**Comment by pburtchaell** [comment]
@SummerWish Perhaps you should checkout the discussion in issue #35.
