### ISSUE TITLE
Unhandled promise rejection 

### ISSUE THREAD

**Issue by pathsny** [pburtchaell/redux-promise-middleware#75]
I have a question about what happens when the payload is a promise that is rejected. I see that the middleware correctly dispatches an event with the _REJECTED suffix.

However, I also see a log entry in the console about an unhandled rejection. This is coming from es6.promise. I dont understand why this is considered unhandled, considering that the middleware has dealt with the promise rejection. Is there something I'm supposed to be doing here?

**Comment by tomatau** [comment]
Which version are you using?

**Comment by pathsny** [comment]
3.0.0

**Comment by trollknurr** [comment]
+1 for answer

**Comment by pburtchaell** [comment]
@pathsny @trollknurr The middleware dispatches a rejected action, but this does not actually handle the rejection. My suggestion would be to either (a) create a second middleware, following the promise middleware, that globally handles all errors; or (b) handle the rejection in the action creator, if you are using thunk middleware.

```
// Example with thunk middleware
export function fooActionCreator() {
  return dispatch => dispatch({
    type: 'FOO_ACTION',
    payload: Promise.reject()
  }).catch(...);
}
```

The reason this middleware does not handle the rejection is because it takes responsibility for dispatching actions only. It is designed to avoid swallowing errors. 

Please let me know if this answers your question! Also, sorry for the delay, but I was engaged with finals at school, relocating to CA for a new job and finishing up other work commitments.

**Comment by pathsny** [comment]
I respectfully disagree with the design decision. 

1. The middleware isnt really swallowing the error since you are dispatching a REJECTED action allowing the reducer to handle the error, so forcing users to add a catch to every promise is a bit silly
2. If users want to catch the rejected promise, the can still do so by catching the promise and doing what's necessary and then rethrowing so that it can be handled by the middleware.

If you really believe that it's necessary to provide users the option to be able to catch a rejected promise, can I suggest adding an option at middleware choice time to turn this off globally?

**Comment by pburtchaell** [comment]
> forcing users to add a catch to every promise is a bit silly

You are right, it is not a practical solution. The more practical solution is to build global handling into a middleware. In my opinion, however, building global handling built into the promise middleware doesn't make sense. Instead, I would refer to my suggestion in the previous comment: "create a second middleware, following the promise middleware, that globally handles all errors/rejected promises."

> If you really believe that it's necessary to provide users the option to be able to catch a rejected promise, can I suggest adding an option at middleware choice time to turn this off globally?

I'm open to exploring changes the middleware, but I don't have time in my schedule now. Addtionally, I don't believe the proposed change makes sense, so I don't want to invest time into it. If you have time and can make some examples, we can go from there.

1. Create an example explicitly demonstrating the current behavior you wish to avoid
2. Create an example with the change to the middleware to prevent the behavior  

This would give me a better understanding of how you wish to change the middleware.

**Comment by tomatau** [comment]
@pathsny -- what harm comes from an unhandled promise rejection error? The appropriate actions are updated so the app state can react and remain resilient... but what problem would an error in the console cause? I think the errors being propagated are actually useful for debugging -- rather than the promise middleware eating them up (like it used to)

**Comment by pathsny** [comment]
The harm is merely annoyance in development. Unnecessary log spew tends to
lead to blindness towards actual unhandled errors. I tend to think of these
errors as handled because the reducer is informed about them and updates
the state appropriately

**Comment by pburtchaell** [comment]
@pathsny I would suggest implementing the global middleware if you want to avoid the annoyance. I don't find it very productive to consider this an actual issue with the project though.

**Comment by pathsny** [comment]
I understand. Thanks, I'll look into that

**Comment by DoubleU23** [comment]
i also don't understand why this behaviour was changed.
i had to fallback to v2.2.3 where the thrown errors (rejected promises) are handled as expected.

if the promise is rejected, the middleware dispatches the _ERROR action with
error: true
payload: the thrown error/rejected value

IMHO thats the way to go

**Comment by pburtchaell** [comment]
@DoubleU23 The current version, as do all versions of the middleware, dispatch the rejected action with `error: true` and the error as the payload. The middleware is not responsible for catching the rejected value. That results in swallowed errors and is not a good practice.
