### ISSUE TITLE
how create a simple action with this middleware in a dedicate action file

### ISSUE THREAD

**Issue by craigcosmo** [pburtchaell/redux-promise-middleware#98]
this is my store

```jsx
import {applyMiddleware, createStore} from 'redux'
import logger from 'redux-logger'
import thunk from 'redux-thunk'
import axios from 'axios'

const reducer = (state ={}, action) => {
	return state
}
const middleware = applyMiddleware(thunk,logger())
const store = createStore(reducer, middleware)

store.dispatch( 
	type:'FETCH_USER',
	payload: axios.get('http://rest.learncode.academy/api/wstern/users')
})
```

As you can see the fectch user action automatic dispatch by store when page load. What I want to do is I want move the fetcth_user action into it own file, lets call it userAction.js. And then dispatch fetch user in home.js page at componentDidMount cycle. How would do that?

**Comment by pburtchaell** [comment]
> What I want to do is I want move the fetcth_user action into it own file, lets call it userAction.js. And then dispatch fetch user in home.js page at componentDidMount cycle. 

This question is unrelated to the middleware. 

> How would do that?

This is not specific to this middleware; you are asking me to explain how to write general React and Redux code, which I can't do. **It is not the responsibility of open source maintainers and contributors to teach others how to code.** Instead of asking a question, you should first [search on GitHub for "redux examples"](https://github.com/search?utf8=✓&q=redux+example) and read [the Redux documentation](http://redux.js.org). If after searching you are still stuck, you should ask a community like [Reactiflux](http://www.reactiflux.com). If you have any specific questions related to this middleware, please do open an issue here.
